# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  redis:
    redisson:
      config: "classpath:/redisson.json"
