spring:
  kafka:
    bootstrap-servers: "192.168.99.114:9092,192.168.99.114:9093,192.168.99.114:9094"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    consumer:
      group-id: "spring-examples"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    admin:
      fail-fast: true
