# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  aop:
    auto: true
  main:
    banner-mode: log
    allow-bean-definition-overriding: true
  banner:
    location: banner.txt
  jackson:
    locale: "zh_CN"
    time-zone: "${TZ:Asia/Shanghai}"
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    joda-date-time-format: ${spring.jackson.date-format}
    default-property-inclusion: always
    serialization:
      indent-output: true
      fail-on-self-references: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-null-map-values: true
      write-empty-json-arrays: true
      write-single-elem-arrays-unwrapped: false
      write-enums-using-to-string: true
    deserialization:
      fail-on-unknown-properties: false
  jmx:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: "/"
  error:
    path: "/error"
  ssl:
    enabled: false
    key-alias: "tomcat"
    key-store-password: "tomcat"
    key-store: "classpath:ssl/keystore.p12"
    key-store-type: PKCS12
