spring:
  aop:
    auto: true
  main:
    web-application-type: servlet
    banner-mode: off
    allow-bean-definition-overriding: true
    lazy-initialization: false
    log-startup-info: true
    cloud-platform: none
    register-shutdown-hook: true
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://192.168.10.115:3306/playground?useSSL=false&allowPublicKeyRetrieval=true"
    username: "playground"
    password: "playground"
    hikari:
      connection-test-query: "SELECT 1"
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: true
    repeatable-sql-migration-prefix: "R"
    sql-migration-prefix: "V"
    sql-migration-suffixes: ".sql"
    url: "${spring.datasource.url}"
    user: "${spring.datasource.username}"
    password: "${spring.datasource.password}"
    locations:
      - "classpath:flyway/"
    baseline-on-migrate: true
    baseline-version: "2021_05_25"
