# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://10.211.55.27:3306/test?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
    username: "root"
    password: "root"

# ----------------------------------------------------------------------------------------------------------------------
# mybatis
# ----------------------------------------------------------------------------------------------------------------------
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: none
      table-prefix: "t_"
      table-underline: true
  type-aliases-package: "spring.examples.mybatis.domain"
  mapper-locations:
    - "classpath*:/mybatis-mapper/**/*.xml"
