spring:
  activemq:
    broker-url: "failover:(tcp://192.168.201.23:61616,tcp://192.168.201.24:61616,tcp://192.168.101.25:61616)?randomize=false"
    user: "guangu"
    password: "D51cX4PcAbmlfaE3"
    in-memory: true
    pool:
      enabled: false
