# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  redis:
    database: 0
    host: "10.211.55.18"
    password: "133810"
  cache:
    type: redis
