# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  redis:
    database: 0
    host: "10.211.55.3"
    port: 6370
    password: "root"
  cache:
    type: redis
    cache-names:
      - users
