# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    shutdown:
      enabled: false
    health:
      enabled: true
      show-details: always
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
  info:
    git:
      enabled: true
      mode: full
  health:
    probes:
      enabled: true
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
        exclude:
          - "shutdown"
