server:
  port: 443
  servlet:
    context-path: "/"
  ssl:
    enabled: true
    key-alias: "tomcat"
    key-store-password: "tomcat"
    key-store: "classpath:META-INF/keystore.p12"
    key-store-type: PKCS12
