# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
jasypt:
  encryptor:
    password: "fallout"
    property:
      prefix: "ENC("
      suffix: ")"
