# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 5MB
