# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  redis:
    host: "10.211.55.3"
    port: 6379
    database: 0
    password: "root"
