# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "rabbitmq-hello"

  rabbitmq:
    host: "10.211.55.26"
    port: 5672
    username: "admin"
    password: "admin"
