# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  rabbitmq:
    host: "192.168.10.115"
    port: 5672
    username: "root"
    password: "root"
    virtual-host: "/"
    listener:
      simple:
        acknowledge-mode: manual
