# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  rabbitmq:
    host: "10.211.55.26"
    port: 5672
    username: "admin"
    password: "admin"
    virtual-host: "/"
    listener:
      simple:
        acknowledge-mode: manual
