# ----------------------------------------------------------------------------------------------------------------------
# springdoc 配置
# ----------------------------------------------------------------------------------------------------------------------
springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    operations-sorter: "method"
    disable-swagger-default-url: true
  api-docs:
    enabled: true
    path: "/api-docs"
  packages-to-scan:
    - "spring.examples.springdoc"
