# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
spring:
  datasource:
    url: "jdbc:mysql://10.211.55.18:3306/test?useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
    username: "root"
    password: "root"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
        hibernate:
          format_sql: true
          enable_lazy_load_no_trans: true
