# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------

spring:
  data:
    mongodb:
#      uri: "mongodb://admin:test@192.168.201.27:27018,192.168.201.28:27018,192.168.201.29:27018/test?authSource=admin"
      uri: "mongodb://admin:123456@10.211.55.3:27017/lbs?authSource=admin"
