# ----------------------------------------------------------------------------------------------------------------------
# Actuator配置
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
